name: Deploy HTML Template

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t vinayreddy143/html-template:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push vinayreddy143/html-template:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull vinayreddy143/html-template:latest
          docker stop html-template || true
          docker rm html-template || true
          docker run -d -p 80:80 --name html-template vinayreddy143/html-template:latest
